//-----AUTH-----

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

//-----USERS-----

export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST'
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS'
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL'

export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL'

//-----USERS-----

export const UPDATE_RECRUITER_PROFILE_REQUEST = 'UPDATE_RECRUITER_PROFILE_REQUEST'
export const UPDATE_RECRUITER_PROFILE_SUCCESS = 'UPDATE_RECRUITER_PROFILE_SUCCESS'
export const UPDATE_RECRUITER_PROFILE_FAIL = 'UPDATE_RECRUITER_PROFILE_FAIL'

export const FETCH_RECRUITER_PROFILE_REQUEST = 'FETCH_RECRUITER_PROFILE_REQUEST'
export const FETCH_RECRUITER_PROFILE_SUCCESS = 'FETCH_RECRUITER_PROFILE_SUCCESS'
export const FETCH_RECRUITER_PROFILE_FAIL = 'FETCH_RECRUITER_PROFILE_FAIL'

//-----JOBS-----

export const FETCH_JOBS_REQUEST = 'FETCH_JOBS_REQUEST'
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL'

export const FETCH_SINGLE_JOB_REQUEST = 'FETCH_SINGLE_JOB_REQUEST'
export const FETCH_SINGLE_JOB_SUCCESS = 'FETCH_SINGLE_JOB_SUCCESS'
export const FETCH_SINGLE_JOB_FAIL = 'FETCH_SINGLE_JOB_FAIL'

export const FETCH_MY_JOB_OFFER_REQUEST = 'FETCH_MY_JOB_OFFER_REQUEST'
export const FETCH_MY_JOB_OFFER_SUCCESS = 'FETCH_MY_JOB_OFFER_SUCCESS'
export const FETCH_MY_JOB_OFFER_FAIL = 'FETCH_MY_JOB_OFFER_FAIL'

export const DELETE_JOB_REQUEST = 'DELETE_JOB_REQUEST'
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS'
export const DELETE_JOB_FAIL = 'DELETE_JOB_FAIL'

export const UPDATE_JOB_REQUEST = 'UPDATE_JOB_REQUEST'
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS'
export const UPDATE_JOB_FAIL = 'UPDATE_JOB_FAIL'

export const CREATE_JOB_REQUEST = 'CREATE_JOB_REQUEST'
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS'
export const CREATE_JOB_FAIL = 'CREATE_JOB_FAIL'

export const SEARCH_JOBS_REQUEST = 'SEARCH_JOBS_REQUEST'
export const SEARCH_JOBS_SUCCESS = 'SEARCH_JOBS_SUCCESS'
export const SEARCH_JOBS_FAIL = 'SEARCH_JOBS_FAIL'

//-----POSTU-----

export const CREATE_POSTU_REQUEST = 'CREATE_POSTU_REQUEST'
export const CREATE_POSTU_SUCCESS = 'CREATE_POSTU_SUCCESS'
export const CREATE_POSTU_FAIL = 'CREATE_POSTU_FAIL'

export const FETCH_POSTU_REQUEST = 'FETCH_POSTU_REQUEST'
export const FETCH_POSTU_SUCCESS = 'FETCH_POSTU_SUCCESS'
export const FETCH_POSTU_FAIL = 'FETCH_POSTU_FAIL'

export const DELETE_POSTU_REQUEST = 'DELETE_POSTU_REQUEST'
export const DELETE_POSTU_SUCCESS = 'DELETE_POSTU_SUCCESS'
export const DELETE_POSTU_FAIL = 'DELETE_POSTU_FAIL'

